// Machine Action Types
export const SET_MACHINE_LOADING = 'SET_MACHINE_LOADING';
export const NEW_MACHINE_CREATED = 'NEW_MACHINE_CREATED';
export const SUCCESS_GETTING_MACHINES = 'SUCCESS_GETTING_MACHINES';
export const LOAD_MACHINE = 'LOAD_MACHINE';
export const EMPTY_NEW_IDS = 'EMPTY_NEW_IDS';

// Stator Action Types
export const INIT_STATOR_PARAMS = 'INIT_STATOR_PARAMS';
export const SET_STATOR_LAMINATION_DATA = 'SET_STATOR_LAMINATION_DATA';
export const SET_STATOR_LAMINATION_PARAM = 'SET_STATOR_LAMINATION_PARAM';
export const SET_STATOR_LAMINATION_TYPE = 'SET_STATOR_LAMINATION_TYPE';
export const SET_STATOR_SLOT_DATA = 'SET_STATOR_SLOT_DATA';
export const SET_STATOR_SLOT_PARAM = 'SET_STATOR_SLOT_PARAM';
export const SET_STATOR_SLOT_TYPE = 'SET_STATOR_SLOT_TYPE';
export const SET_STATOR_SLOT_IMAGE_URL = 'SET_STATOR_SLOT_IMAGE_URL';
export const SET_STATOR_CONDUCTOR_DATA = 'SET_STATOR_CONDUCTOR_DATA';
export const SET_STATOR_CONDUCTOR_PARAM = 'SET_STATOR_CONDUCTOR_PARAM';
export const SET_STATOR_CONDUCTOR_TYPE = 'SET_STATOR_CONDUCTOR_TYPE';
export const SET_STATOR_CONDUCTOR_IMAGE_URL = 'SET_STATOR_CONDUCTOR_IMAGE_URL';
export const SET_STATOR_MAIN_IMAGE_URL = 'SET_STATOR_MAIN_IMAGE_URL';

// Rotor Action Types
export const INIT_ROTOR_PARAMS = 'INIT_ROTOR_PARAMS';
export const SET_ROTOR_LAMINATION_DATA = 'SET_ROTOR_LAMINATION_DATA';
export const SET_ROTOR_LAMINATION_PARAM = 'SET_ROTOR_LAMINATION_PARAM';
export const SET_ROTOR_LAMINATION_TYPE = 'SET_ROTOR_LAMINATION_TYPE';
export const SET_ROTOR_SLOT_DATA = 'SET_ROTOR_SLOT_DATA';
export const SET_ROTOR_SLOT_PARAM = 'SET_ROTOR_SLOT_PARAM';
export const SET_ROTOR_SLOT_TYPE = 'SET_ROTOR_SLOT_TYPE';
export const SET_ROTOR_SLOT_IMAGE_URL = 'SET_ROTOR_SLOT_IMAGE_URL';
export const SET_ROTOR_CONDUCTOR_DATA = 'SET_ROTOR_CONDUCTOR_DATA';
export const SET_ROTOR_CONDUCTOR_PARAM = 'SET_ROTOR_CONDUCTOR_PARAM';
export const SET_ROTOR_CONDUCTOR_TYPE = 'SET_ROTOR_CONDUCTOR_TYPE';
export const SET_ROTOR_CONDUCTOR_IMAGE_URL = 'SET_ROTOR_CONDUCTOR_IMAGE_URL';
export const SET_ROTOR_HOLE_DATA = 'SET_ROTOR_HOLE_DATA';
export const SET_ROTOR_HOLE_PARAM = 'SET_ROTOR_HOLE_PARAM';
export const SET_ROTOR_HOLE_TYPE = 'SET_ROTOR_HOLE_TYPE';
export const SET_ROTOR_HOLE_IMAGE_URL = 'SET_ROTOR_HOLE_IMAGE_URL';
export const SET_ROTOR_MAIN_IMAGE_URL = 'SET_ROTOR_MAIN_IMAGE_URL';

// Housing Action Types
export const INIT_HOUSING_PARAMS = 'INIT_HOUSING_PARAMS';
export const SET_HOUSING_DATA = 'SET_HOUSING_DATA';
export const SET_HOUSING_PARAM = 'SET_HOUSING_PARAM';
export const SET_HOUSING_TYPE = 'SET_HOUSING_TYPE';
export const SET_HOUSING_IMAGE_URL = 'SET_HOUSING_IMAGE_URL';
export const SET_HOUSING_MAIN_IMAGE_URL = 'SET_HOUSING_MAIN_IMAGE_URL';

// Results Action Types
export const GET_RESULTS_SUCCESS = 'GET_RESULTS_SUCCESS';

// Loss Action Types
export const INIT_LOSS_PARAMS = 'INIT_LOSS_PARAMS';
export const SET_LOSS_DATA = 'SET_LOSS_DATA';
export const SET_LOSS_PARAM = 'SET_LOSS_PARAM';
export const SET_LOSS_TYPE = 'SET_LOSS_TYPE';
export const SET_LOSS_MAIN_IMAGE_URL = 'SET_LOSS_MAIN_IMAGE_URL';
